#### Author of this code: Eva-Maria Ahrer, adapted from Tiberius TransitGPPM model (author: J. Kirk)

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt


class Param(object):
    '''A Param (parameter) needs a starting value and a current value. However, when first defining the Param object, it takes the starting value as the current value.

    Inputs:
    startVal: the starting value for the parameter

    Returns:
    Param object'''
    def __init__(self,startVal):
        self.startVal = startVal
        self.currVal  = startVal



class LightcurveModel(object):
    def __init__(self,flux,flux_error,time_array,prior_file,fit_models,model_inputs):

        """


        Inputs:
        flux              - the light curve flux data points.
        flux_error        - the errors on the flux data points to be fitted.
        time_array        - the array of time
        prior_file        - .txt file with priors
        model_inputs      - input for models
        ld_law            - the limb darkening law we want to use: linear/quadratic/nonlinear/squareroot, default = quadratic


        Can return:
        - model calculated on a certain time array
        - ...
        """

        self.flux_array = flux
        self.flux_err = flux_error
        self.time_array = time_array

        file = pd.read_csv(prior_file, sep='\s+', comment='#')
        currVals = list(file['value'])
        param_names = list(file['Name'])
        fixed = list(file['fitting'])
        self.param_dict = {}
        self.param_list_free  = []
        self.param_list_joint = []
        self.prior_dict = {}
        self.npars = 0

        for i in range(len(param_names)):
            if fixed[i] == 'free':
                self.param_list_free.append(param_names[i])
                self.param_dict[param_names[i]] = Param(currVals[i])
                self.prior_dict[param_names[i]+'_1'] = file['prior_1'][i]
                self.prior_dict[param_names[i]+'_2'] = file['prior_2'][i]
                self.prior_dict[param_names[i]+'_prior'] = file['prior_type'][i]
                self.npars += 1
            elif fixed[i] == 'fixed':
                self.param_dict[param_names[i]] = float(currVals[i])
            elif fixed[i] == 'joint':
                # check the joint parameters are astrophysical
                astro_param_names = ['per','rp','rp2','phi','t0','a','inc','w','ecc']
                if param_names[i] not in astro_param_names:
                    raise SystemError('Joint fitting designated for inappropriate parameters. Check priors txt file.')
                else:
                    print(f'{param_names[i]} will be jointly fit across all light curves.')
                self.param_list_joint.append(param_names[i])
                # add to the free parameters list too
                self.param_list_free.append(param_names[i])
                self.param_dict[param_names[i]] = Param(currVals[i])
                self.prior_dict[param_names[i]+'_1'] = file['prior_1'][i]
                self.prior_dict[param_names[i]+'_2'] = file['prior_2'][i]
                self.prior_dict[param_names[i]+'_prior'] = file['prior_type'][i]
                self.npars += 1 # number of free parameters for this particular light curve (not for joint fit - see joint_fitting.py)
            else:
                print('something is wrong with your prior file')

        # initialise models
        self.transit_model_package = fit_models['transit_model']

        self.systematics_model_methods = fit_models['systematics_model']
        self.systematic_model_inputs = model_inputs['systematic_model']

        self.transit_model_inputs = model_inputs['transit_model']

        if self.transit_model_inputs['use_generated_ld_as_prior'] or self.transit_model_inputs['use_generated_ld']:
            wc,we,u1,u1_err,u2,u2_err,u3,u3_err,u4,u4_err = self.transit_model_inputs['LDCs_generated']
            ldcs = [u1, u2, u3, u4]
            ldcs_errs = [u1_err, u2_err, u3_err, u4_err]
            ld_list = ['u1', 'u2', 'u3', 'u4']
            for i in range(len(ld_list)):
                if ld_list[i] in param_names and ld_list[i] in self.param_list_free:
                    print("\n You're using the limb-darkening coefficients and their uncertainties as generated by a model.")
                    self.param_dict[ld_list[i]] = Param(ldcs[i])
                    if self.transit_model_inputs['use_generated_ld_as_prior']:
                        self.prior_dict[ld_list[i]+'_1'] = ldcs[i]
                        self.prior_dict[ld_list[i]+'_2'] = ldcs_errs[i]
                        self.prior_dict[ld_list[i]+'_prior'] = 'N'
                elif ld_list[i] in param_names and self.transit_model_inputs['use_generated_ld']:
                    print("\n You're fixing your limb-darkening coefficients to the ones generated by a model.")
                    self.param_dict[ld_list[i]] = float(ldcs[i])

        if self.transit_model_package == 'batman':
            from fitting_utils import BatmanModel as bm
            self.transit_model = bm.BatmanModel(self.param_dict, self.param_list_free, self.transit_model_inputs, self.time_array)
        elif self.transit_model_package == 'catwoman':
            from fitting_utils import CatwomanModel as cwm
            self.transit_model = cwm.CatwomanModel(self.param_dict, self.param_list_free, self.transit_model_inputs, self.time_array)
        elif self.transit_model_package == 'fleck':
            from fitting_utils import FleckSpotModel as fsm
            self.transit_model = fsm.FleckModel(self.param_dict, self.param_list_free, self.transit_model_inputs, self.time_array)

        from fitting_utils import systematics_model as sm

        if self.sys_model_used:
            self.systematic_model = sm.SystematicsModel(self.param_dict, self.systematic_model_inputs,
                                                        self.systematics_model_methods, self.time_array)

        
        if 'GP_model' in model_inputs:
            self.gp_model_inputs = model_inputs['GP_model']
            from fitting_utils import GPModel as gpm
            self.GP_model = gpm.GPModel(self.param_dict,self.gp_model_inputs, self.time_array, self.flux_array, self.flux_err)
        else:
            self.GP_used = False

        self.spot_used = False # add spot model here
        if self.spot_used:
            self.spot_model_package = model_inputs['spot_model']


    def return_free_parameter_list(self):
        return self.param_list_free
    def return_joint_parameter_list(self):
        return self.param_list_joint
    def return_parameter_dict(self):
        return self.param_dict

    def calc(self,time=None, with_GP=True):

        """Calculates and returns the evaluated Mandel & Agol transit model, using catwoman.

        Inputs:
        time - the array of times at which to evaluate the model. Can be left blank if this has not changed from the initial init call.
        with_GP - if using a GP also return the model including the GP (or without it)

        Returns:
        model - the full light curve"""

        if time is None:
            time = self.time_array
        
        transit_calc = self.transit_model.calc(time)
        model_calc = np.array(transit_calc)

        sys_calc = self.systematic_model.calc(time)
        model_calc *= sys_calc

        if self.GP_used and with_GP:
            mu, std = self.GP_model.calc(time, model_calc)
            model_calc *= mu

        return model_calc

    def calc_gp_model(self,time=None,decompose=False):
        if time is None:
            time = self.time_array
        model_calc = self.calc(time, with_GP=False)
        return self.GP_model.calc(time, model_calc, deconstruct_gp=decompose)
    
    def update_model(self,theta):

        for i in range(len(theta)):
            self.param_dict[self.param_list_free[i]].currVal = theta[i]

        self.transit_model.update_model(self.param_dict)

        if self.sys_model_used:
            self.systematic_model.update_model(self.param_dict)
        if self.GP_used:
            self.GP_model.update_model(self.param_dict)

        return


    def return_flux_err(self):
        if 'infl_err' in self.param_list_free:
            return self.param_dict['infl_err'].currVal * self.flux_err
        else:
            return self.flux_err


    def calc_residuals(self):
        curr_model = self.calc(self.time_array)
        return self.flux_array - curr_model
